# Generated by Django 3.2.7 on 2021-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=300)),
                ('comment_text', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Main', 'Main'), ('Appetizer', 'Appetizer'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=100)),
                ('food_image', models.ImageField(blank=True, upload_to='static/foodimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_id', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
