# Generated by Django 3.2.7 on 2021-11-13 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='registered_store',
            field=models.ManyToManyField(blank=True, related_name='regisstore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_store',
            field=models.ManyToManyField(blank=True, related_name='comstore', to=settings.AUTH_USER_MODEL),
        ),
    ]
